apiVersion: apps/v1
kind: Deployment
metadata:
  name: reelapp-storage
  namespace: reelapp
  labels:
    app: reelapp-storage
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reelapp-storage
  template:
    metadata:
      name: reelapp-storage
      labels:
        app: reelapp-storage
    spec:
      containers:
        - name: reelapp-storage
          image: simo3011w/reelapp-storage-service:2.0.9
          imagePullPolicy: Always
          ports:
            - containerPort: 9090
              protocol: TCP
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://simo:123@mongodb-service:27017/storage-service?authSource=admin
            - name: MINIO_URL
              value: "http://10.1.1.198:9000"
---
apiVersion: v1
kind: Service
metadata:
  namespace: reelapp
  name: reelapp-storage-service
spec:
  ports:
    - port: 9090
      targetPort: 9090
      nodePort: 32002
  type: NodePort
  selector:
    app: reelapp-storage
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reelapp-storage-ingress
  namespace: reelapp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web

spec:
  rules:
    - host: storage.reelapp.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reelapp-storage-service
                port:
                  number: 9090