apiVersion: apps/v1
kind: Deployment
metadata:
  name: reelapp-user-management
  namespace: reelapp
  labels:
    app: reelapp-user-management
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reelapp-user-management
  template:
    metadata:
      labels:
        app: reelapp-user-management
    spec:
      containers:
        - name: reelapp-user-management
          image: simo3011w/reelapp-user_management-service:main
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              protocol: TCP
          env:
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/Users"
            - name: MINIO_URL
              value: "http://minio-service:9000"
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  namespace: reelapp
  name: reelapp-user-management-service
spec:
  selector:
    app: reelapp-user-management
  type: NodePort
  ports:
    - name: http
      port: 8081
      targetPort: 8081
      nodePort: 32003
