apiVersion: apps/v1
kind: Deployment
metadata:
  name: reelapp-webapp
  namespace: reelapp
  labels:
    app: reelapp-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: reelapp-webapp
  template:
    metadata:
      name: reelapp-webapp
      labels:
        app: reelapp-webapp
    spec:
      containers:
        - name: reelapp-webapp
          image: simo3011w/reelapp-webapp-service:main
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              protocol: TCP
      restartPolicy: Always
---
apiVersion: v1
kind: Service
metadata:
  name: reelapp-webapp-service
  namespace: reelapp
spec:
  selector:
    app: reelapp-webapp
  ports:
    - port: 80
      targetPort: 80
  type: ClusterIP

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: reelapp-webapp-ingress
  namespace: reelapp
  annotations:
    traefik.ingress.kubernetes.io/router.entrypoints: web
spec:
  rules:
    - host: reelapp.localhost
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: reelapp-webapp-service
                port:
                  number: 80

